// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model


type Post struct {
	ID   string `json:"ID"`
	Text string `json:"Text"`
}

type InputPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}



// type NewTodo struct {
// 	Text   string `json:"text"`
// 	UserID string `json:"userId"`
// }

// type Todo struct {
// 	ID     string `gorm:"type:varchar(191)"`
// 	Text   string `json:"text"`
// 	Done   bool   `json:"done"`
// 	UserID string `json:"userId"`
// 	User   *User  `json:"user"`
// }

// type InputTodo struct {
// 	ID   string `json:"id"`
// 	Text string `json:"text"`
// 	Done bool   `json:"done"`
// }
